import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Providers } from "@/components/providers";
import { ThemeToggle } from "@/components/main/theme-toggle";

import { NavBar } from "@/components/nav/nav-bar";
import { Sidebar } from "@/components/sidebar/sidebar";
import { Footer } from "@/components/main/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Rhys' Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="flex flex-col min-h-screen sm:pl-24 pt-24">
            <NavBar />
            <Sidebar />
            {children}
            <Footer />
            <ThemeToggle />
          </div>
        </Providers>
      </body>
    </html>
  );
}
